### PR TITLE
Add ghooks

### PR DESCRIPTION
**Pull request by geekytime**
Add ghooks

Mostly so I don't bork up the mocha.opts file again. :flushed:

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
I've had _so_ many problems with ghooks.  I was dreading this PR. Do we _have_ to? :tired_face:

**Comment by geekytime** [comment]
Yikes! What problems have you had with ghooks?

**Comment by LongLiveCHIEF** [comment]
Do you remember the issues I mentioned you in on the matterfront work?  You never did respond to them, but now I can't find the mentions.

There were commits that passed on your machine, but not mine, even on a clean install.  I couldn't commit anything, even locally, until we solved the problem with ghooks and the test, or until I removed the problematic test.

I don't need every single commit to pass tests. I like having commits that are as clear as possible, and sometimes it takes me 3 commits to make a full change, and the first 2 commits don't pass tests, (but the 3rd does.)

The other reason for this, is that I prefer to write tests first, and commit the tests in one commit, and then the new feature or fix code in the second commit.  ghooks prevents this.

**Comment by LongLiveCHIEF** [comment]
can you make it an optional dependency instead?

**Pull request merged**
