### PR TITLE
add basic travis config

### PR DESCRIPTION
**Pull request by geekytime**

### CODE REVIEW

**Comment by geekytime** [comment]
closes #3

**Comment by LongLiveCHIEF** [comment]
Are we going to have problems with the travis config `4` for node version, and using scoped packages (due to our org) with npm 2?

**Comment by geekytime** [comment]
I don't think so. The script upgrade to npm3. We can switch to 5 if you want, I just figured supporting 4 was nice because lots of folks are probably still on 4.

**Comment by LongLiveCHIEF** [comment]
I was worried about the use of template strings, but looks like it's supported without the `--harmony` flag now. I have `nvm` on my system, and I ran everything using `4.1`, and everything is green so far, so I'm ok with v4.

:+1:

**Pull request merged**
